// project-settlement-front-main/project-settlement-front-main/src/views/Transactions.vue
<script setup>
import {computed, onMounted, ref, watch} from "vue";
import useCenters from "/src/composables/useCenters.js";
import useUploads from "/src/composables/useUploads.js";
import RecursiveRow from "/src/components/RecursiveRow.vue";
import {useAuthStore} from "/src/stores/auth.js";
import DateFilter from "../components/FilterDate.vue";
import UserSelect from "../components/UserSelect.vue";
import Pagination from "../components/Pagination.vue";
import Confirm from "../components/modals/Confirm.vue";
import {useFilterStore} from "/src/stores/filter.js";
import {useRoute} from "vue-router";
import axios from "/src/interceptors/axios";

const filterStore = useFilterStore();
const {filter} = filterStore;
const route = useRoute();

const {
  records,
  getFees,
  currentPage,
  totalPages,
  totalElements,
  pageSize,
  withdrawTypes,
  sortOptions,
  sortByDir,
  formatDate,
} = useUploads()

const {
  getRegionsByParentId,
  _regions,
  _serviceCenters,
  updateRecord,
  extractionFee,
  handleEditClick,
  divide,
  sc,
  getServiceCenters,
  deleteRecord
} = useCenters()

const _error = ref(false)
const wasCleared = ref(false)

const handleClearClick = () => {
  wasCleared.value = true;
  _error.value = false;
  extractionFee.value.orderN = '';
  extractionFee.value.orderStatus = null;
  extractionFee.value.projectID = '';
  extractionFee.value.withdrawType = 'აირჩიეთ ტიპი';
  extractionFee.value.paymentOrderSentDate = null;
  extractionFee.value.treasuryRefundDate = null;
  extractionFee.value.clarificationDate = null;
  extractionFee.value.note = '';
  searchTerm.value = '';
  extractionFee.value.region = 'აირჩიეთ რეგიონი';
  extractionFee.value.serviceCenter = 'აირჩიეთ მ/ც';
  canceledProject.value = '';
};

const handleSaveClick = async () => {
  const {region, withdrawType, serviceCenter, projectID, orderN} = extractionFee.value;
  const isRefund = withdrawType === '6 (თანხის დაბრუნება)';
  const isAdmin = authStore.user.role === 'ROLE_ADMIN';

  // ორდერის N "N/A" — მ/ც და პროექტის N სავალდებულო აღარ არის (ნებისმიერი ტიპისთვის)
  const isTypeException = (orderN ?? '').trim().toUpperCase() === 'N/A';

  // --- Validation Checks ---
  const isRegionInvalid = !isRefund && region === 'აირჩიეთ რეგიონი';
  const isServiceCenterInvalid = !isRefund && serviceCenter === 'აირჩიეთ მ/ც';
  const isWithdrawTypeInvalid = withdrawType === 'აირჩიეთ ტიპი';
  const isProjectInvalid = !isAdmin && !projectID;

  const isInvalid = isRegionInvalid || isServiceCenterInvalid || isWithdrawTypeInvalid || isProjectInvalid;

  const performSaveActions = async () => {
    const trimmedString = canceledProject.value.trim();
    extractionFee.value.canceledProject = trimmedString === ''
        ? []
        : trimmedString.split(/\s+/);
    canceledProject.value = '';
    wasCleared.value = false;
    await updateRecord();
    await getFees();
    searchTerm.value = '';
    document.getElementById('my_modal_1').close();
  };

  const clearPlaceholders = () => {
    if (extractionFee.value.region === 'აირჩიეთ რეგიონი' || extractionFee.value.region === '') {
      extractionFee.value.region = '';
    }
    if (extractionFee.value.serviceCenter === 'აირჩიეთ მ/ც') {
      extractionFee.value.serviceCenter = '';
    }
    if (extractionFee.value.withdrawType === 'აირჩიეთ ტიპი') {
      extractionFee.value.withdrawType = '';
    }
  };

  if (wasCleared.value) {
    clearPlaceholders();
    await performSaveActions();
  } else if (isTypeException) {
    clearPlaceholders();
    // ეს თანხა გამოუყენებლად ვერ ჩაითვლება — სტატუსი ავტომატურად ხდება შევსებული
    if (!extractionFee.value.orderStatus || extractionFee.value.orderStatus === 'ORDER_INCOMPLETE') {
      extractionFee.value.orderStatus = 'ORDER_COMPLETE';
    }
    await performSaveActions();
  } else if (isInvalid) {
    if (canceledProject.value) {
      clearPlaceholders();
      await performSaveActions();
    } else {
      _error.value = true;
    }
  } else {
    await performSaveActions();
  }
};

const hdc = async () => {
  canceledProject.value = '';
  await deleteRecord();
  await getFees();
  document.getElementById('my_modal_1').close()
}
const hec = async (extraction) => {
  _error.value = false;
  searchTerm.value = extraction.serviceCenter;
  canceledProject.value = extraction.canceledProject.join(" ");
  await handleEditClick(extraction)
}

const id = ref()
const amount = ref('')
const remainder = ref();
const error = ref(false)
watch(amount, (newAmount) => {
  error.value = remainder.value < newAmount;
})


const handleDivideClick = async (args) => {
  document.getElementById('my_modal_7').showModal()
  id.value = args[0];
  remainder.value = args[1];
}


const handleDivision = async () => {
  if (remainder < amount.value) {
    error.value = true;
    return;
  }
  await divide(id.value, mapToArray())
  await getFees()
  id.value = undefined;
  amount.value = '';
  remainder.value = undefined;
  error.value = false;
}


onMounted(async () => {
  await getRegionsByParentId();
  await getFees();
  await getServiceCenters()
})

const regex = /^(\d+(\.\d+)?(\s\d+(\.\d+)?)*)$/;
const cleanAmount = () => amount.value.replace(/\s+/g, ' ').trim();
const mapToArray = () => cleanAmount().split(' ').map(Number);
const sumArray = () => mapToArray().reduce((a, b) => a + b, 0);
const validateAmount = () => {
  const numbers = mapToArray();
  return regex.test(cleanAmount()) && numbers.every(n => n > 0) && (sumArray() <= remainder.value);
};

const authStore = useAuthStore();

watch(currentPage, async (value) => {
      if (value > totalPages) {
        currentPage.value = totalPages.value;
      }
      if (value) {
        await getFees();
      }
    }
)

const searchTerm = ref('');
const isDropdownOpen = ref(false);

const filteredServiceCenters = computed(() =>
    sc.value.filter(center => center.name.toLowerCase().includes(searchTerm.value))
);

function selectCenter(centerName, parentName) {
  extractionFee.value.serviceCenter = centerName;
  searchTerm.value = centerName;
  extractionFee.value.region = parentName;
  isDropdownOpen.value = false;
}

function closeDropdown() {
  setTimeout(() => isDropdownOpen.value = false, 200);
}

const clearRegion = () => {
  filter.region = 'აირჩიეთ რეგიონი';
  _serviceCenters.value = [];
  clearSC();
}

const clearSC = () => {
  filter.serviceCenter = 'აირჩიეთ მ/ც';
}

const clearType = () => {
  filter.withdrawType = [];
}

const clearStatus = () => {
  filter.status = 'ჩანაწერის სტატუსი';
}

const clearOrderStatus = () => {
  filter.orderStatus = 'ორდერის სტატუსი';
}

const clearClarification = () => {
  filter.clarificationDateStart = undefined;
  filter.clarificationDateEnd = undefined;
}

/*const clearChange = () => {
  filter.changeDateStart = undefined;
  filter.changeDateEnd = undefined;
}*/

const clearTransfer = () => {
  filter.transferDateStart = undefined;
  filter.transferDateEnd = undefined;
}

const clearExtraction = () => {
  filter.extractionDateStart = undefined;
  filter.extractionDateEnd = undefined;
}

const clearSortByDir = () => {
  sortByDir.value = sortOptions[16];
}

const handleClear = async () => {
  filterStore.clearFilter();
  _serviceCenters.value = [];
  clearSortByDir();
  await handleFilter();
}

const handleFilter = async () => {
  currentPage.value = 1;
  await getFees();
}

async function getSelectedParentId(event) {
  await getRegionsByParentId(Number(event.target.selectedOptions[0].getAttribute('data-id')));
}

const isVisible = ref(false);

const toggleType = (type) => {
  const index = filter.withdrawType.indexOf(type);
  if (index === -1) {
    filter.withdrawType.push(type);
  } else {
    filter.withdrawType.splice(index, 1);
  }
};

const isTypeDropdownOpen = ref(false);
const closeTypeDropdown = () => {
  isTypeDropdownOpen.value = false;
}

function extractStartingNumber(type) {
  if (type === 'null') {
    return type;
  } else {
    const match = type.match(/^\d+/);
    return match[0]
  }
}

const canceledProject = ref('');

const similarPayments = ref([]);
const similarPage = ref(1);
const similarPageSize = ref(10);
const similarTotalPages = ref(0);
const similarTotalElements = ref(0);
const similarLoading = ref(false);

const fetchSimilarPayments = async () => {
  if (!extractionFee.value || !extractionFee.value.tax) return;
  similarLoading.value = true;
  try {
    const {data} = await axios.get(`connection-fees/by-taxpayer`, {
      params: {
        taxPayerId: extractionFee.value.tax,
        page: similarPage.value,
        size: similarPageSize.value
      }
    });
    similarPayments.value = data.content;
    similarTotalPages.value = data.page.totalPages;
    similarTotalElements.value = data.page.totalElements;
  } catch (e) {
    console.error(e);
  } finally {
    similarLoading.value = false;
  }
}

watch(similarPage, () => {
  fetchSimilarPayments();
});

watch(similarPageSize, () => {
  if (similarPage.value === 1) {
    fetchSimilarPayments();
  } else {
    similarPage.value = 1;
  }
});
</script>

<template>
  <!-- Toggle using an icon (Chevron) -->
  <div @click="isVisible = !isVisible" class="cursor-pointer flex items-center mb-2.5">
    <span class="mr-2">
      <i :class="isVisible ? 'fas fa-chevron-up' : 'fas fa-chevron-down'"></i>
    </span>
    <span class="font-bold text-sm">ფილტრები</span> <!-- Optional label if you want to have text as well -->
  </div>

  <transition>
    <!--ფილტრი-->
    <div v-if="isVisible" class="flex flex-col gap-y-5">
      <!--პირველი ხაზი-->
      <div class="filter-row">
        <!--რეგიონი-->
        <div class="select-container">
          <select class="filter-select" v-model="filter.region" @change="getSelectedParentId">
            <option disabled selected>აირჩიეთ რეგიონი</option>

            <option :value="region.name" v-for="(region, index) in _regions" v-text="region.name" :data-id="region.id"
                    :key="index"/>
          </select>

          <button class="filter-clear-btn" @click="clearRegion">✕</button>
        </div>
        <!--რეგიონი-->

        <!--მ/ც-->
        <div class="select-container">
          <select class="filter-select" v-model="filter.serviceCenter">
            <option disabled selected>აირჩიეთ მ/ც</option>

            <option :value="center.name" v-for="(center, index) in _serviceCenters" v-text="center.name" :key="index"/>
          </select>

          <button class="filter-clear-btn" @click="clearSC">✕</button>
        </div>
        <!--მ/ც-->

        <!--ტიპი-->
        <div class="relative select-container">
          <input type="text" @click="isTypeDropdownOpen = !isTypeDropdownOpen" placeholder="აირჩიეთ ტიპი"
                 class="input input-bordered input-sm focus:outline-0 filter-select cursor-pointer" readonly/>

          <button class="filter-clear-btn" @click="clearType(); isTypeDropdownOpen = false">✕</button>

          <div v-if="isTypeDropdownOpen"
               class="absolute z-10 bg-white border border-gray-300 rounded-md shadow-lg max-w-xs top-9">
            <div v-for="(type, index) in withdrawTypes" :key="index"
                 class="p-2 hover:bg-gray-100 cursor-pointer text-sm">
              <label class="flex items-center space-x-2">
                <input type="checkbox" class="checkbox checkbox-xs" :value="extractStartingNumber(type)"
                       :checked="filter.withdrawType.includes(extractStartingNumber(type))"
                       @change="toggleType(extractStartingNumber(type))"/>
                <span>{{ (index !== 16) ? type : "უცნობი ტიპი" }}</span>
              </label>
            </div>
          </div>
        </div>
        <!--ტიპი-->

        <!--სტატუსი-->
        <div class="flex">
          <div class="select-container" title="ორდერის სტატუსი">
            <select class="filter-select" v-model="filter.orderStatus">
              <option disabled selected>ორდერის სტატუსი</option>

              <option value="ORDER_INCOMPLETE">გამოუყენებელი</option>

              <option value="ORDER_COMPLETE">შევსებული</option>

              <option value="YELLOW_AMOUNT">დასასრულებელი</option>

              <option value="CANCELED">გაუქმებული</option>

              <option value="IN_PROGRESS">პროცესში</option>

              <option value="RETURNED">დაბრუნებული</option>

              <!--<option value="SOFT_DELETED">წაშლილები</option>-->
            </select>

            <button class="filter-clear-btn" @click="clearOrderStatus">✕</button>
          </div>


          <div class="select-container" title="ჩანაწერის სტატუსი">
            <select class="filter-select" v-model="filter.status">
              <option disabled selected>ჩანაწერის სტატუსი</option>

              <option value="TRANSFER_COMPLETE">შევსებული</option>

              <option value="TRANSFERRED">შესავსები</option>

              <option value="CANCELED">გაუქმებული</option>

              <!--<option value="SOFT_DELETED">წაშლილები</option>-->
            </select>

            <button class="filter-clear-btn" @click="clearStatus">✕</button>
          </div>
        </div>
        <!--სტატუსი-->

        <!--ბრუნვა-->
        <div class="grid grid-cols-3 items-center gap-x-8">
          <p class="filter-label">ბრუნვა (კრედ)</p>

          <input type="text" class="filter-input" placeholder="მინ" v-model="filter.totalAmountStart"/>

          <input type="text" class="filter-input" placeholder="მაქს" v-model="filter.totalAmountEnd"/>
        </div>
        <!--ბრუნვა-->
      </div>
      <!--პირველი ხაზი-->

      <!--მეორე ხაზი-->
      <div class="filter-row">
        <!--ორდერის N-->
        <input type="text" class="filter-input" v-model="filter.orderN"
               placeholder="ორდერის N (მრავლობითი: 123 456 789)"/>
        <!--ორდერის N-->

        <!--პროექტის N-->
        <input type="text" class="filter-input" v-model="filter.projectID" placeholder="პროექტის N"/>
        <!--პროექტის N-->

        <!--N-->
        <input type="text" class="filter-input" v-model="filter.id" placeholder="N"/>
        <!--N-->

        <!--დანიშნულება-->
        <input type="text" class="filter-input" v-model="filter.purpose" placeholder="დანიშნულება"/>
        <!--დანიშნულება-->

        <!--ID-->
        <input type="text" class="filter-input" v-model="filter.tax" placeholder="ID"/>
        <!--ID-->
      </div>
      <!--მეორე ხაზი-->

      <div class="filter-row">
        <!--დამატებითი ინფორმაცია-->
        <input type="text" class="input input-bordered input-sm focus:outline-0 w-[86%]" v-model="filter.description"
               placeholder="დამატებითი ინფორმაცია"/>
        <!--დამატებითი ინფორმაცია-->

        <user-select v-model="filter.change_person"/>

        <date-filter v-model:start-date="filter.clarificationDateStart" v-model:end-date="filter.clarificationDateEnd"
                     label="გარკვევის თარიღი" @clear="clearClarification"/>

        <!--<date-filter v-model:start-date="filter.changeDateStart" v-model:end-date="filter.changeDateEnd"
          label="ცვლილების თარიღი" @clear="clearChange" />-->

        <date-filter v-model:start-date="filter.transferDateStart" v-model:end-date="filter.transferDateEnd"
                     label="გადმოტანის თარიღი" @clear="clearTransfer"/>

        <date-filter v-model:start-date="filter.extractionDateStart" v-model:end-date="filter.extractionDateEnd"
                     label="ჩარიცხვის თარიღი" @clear="clearExtraction"/>
      </div>

      <!--მესამე ხაზი-->
      <div class="filter-row">
        <input type="text" class="input input-bordered w-[85%] input-sm focus:outline-0" v-model="filter.note"
               placeholder="შენიშვნა"/>

        <div class="select-container">
          <select class="select select-bordered select-sm w-full focus:outline-0" v-model="sortByDir">
            <option disabled>დალაგება</option>
            <option :value="option" v-for="(option, index) in sortOptions" v-text="option.text" :key="index"/>
          </select>
          <button class="filter-clear-btn" @click="clearSortByDir">✕</button>
        </div>


        <!--History Id-->
        <input type="text" class="filter-input" v-model="filter.history" placeholder="History Id"/>
        <!--History Id-->

        <div class="flex gap-x-2">
          <button class="btn btn-neutral btn-sm" @click="handleFilter">გაფილტვრა</button>
          <button class="btn btn-neutral btn-sm" @click="handleClear">გასუფთავება</button>
        </div>
      </div>
      <!--მესამე ხაზი-->
    </div>
    <!--ფილტრი-->
  </transition>

  <!--ცხრილი-->
  <div class="flex flex-col gap-y-5 mt-5">
    <table class="table table-xs">
      <thead>
      <tr>
        <th v-if="authStore.user"/>

        <th>N</th>

        <th>ორდერის N</th>

        <th>რეგიონი</th>

        <th>მ/ც</th>

        <th>პროექტის N</th>

        <th>ტიპი</th>

        <th>ბრუნვა (კრედ)</th>

        <th>დანიშნულება</th>

        <th>დამატებითი ინფორმაცია</th>

        <th>ID</th>

        <th>ჩარიცხვის თარიღი</th>

        <th>გარკვევის თარიღი</th>

        <!--<th>ცვლილების თარიღი</th>-->

        <th>თანხის დაბრუნების <br/> მოთხოვნის თარიღი</th>

        <th>საგადახდო დავალების <br/> მიღების თარიღი</th>

        <th>History Id</th>

        <th>შემცვლელი</th>
      </tr>
      </thead>
      <tbody v-if="records && records.length > 0">
      <RecursiveRow @handleDivideClick="handleDivideClick" @handleEditClick="hec" :records="records"/>
      </tbody>

      <tbody v-else-if="records && records.length === 0">
      <tr>
        <td>
          ჩანაწერები ვერ მოიძებნა!
        </td>
      </tr>
      </tbody>

      <tbody v-else>
      <tr>
        <td class="flex items-center gap-x-2.5">
          იტვირთება <span class="loading loading-spinner loading-md"/>
        </td>
      </tr>
      </tbody>
    </table>
    <!--ცხრილი-->

    <pagination v-model:current-page="currentPage" v-model:page-size="pageSize" v-model:total-pages="totalPages"
                v-model:total-elements="totalElements"/>
  </div>

  <dialog id="my_modal_1" class="modal">
    <div class="modal-box max-w-[45vw] flex flex-col gap-y-3 text-sm" v-if="extractionFee">
      <div class="flex gap-x-20">
        <!-- Left Column -->
        <div class="flex flex-col w-1/2 gap-y-2">
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">ორდერის N</label>
            <div class="grid grid-cols-2 gap-x-2 max-w-xs">
              <input type="text" class="input input-bordered w-full max-w-xs input-sm focus:outline-0"
                     v-model="extractionFee.orderN"/>
              <select class="filter-select" v-model="extractionFee.orderStatus">
                <!--<option disabled selected>აირჩიეთ ორდერის ტიპი</option>-->

                <option value="ORDER_INCOMPLETE">გამოუყენებელი</option>

                <option value="ORDER_COMPLETE">შევსებული</option>

                <option value="YELLOW_AMOUNT">დასასრულებელი</option>

                <option value="CANCELED">გაუქმებული</option>

                <option value="IN_PROGRESS">პროცესში</option>

                <option value="RETURNED">დაბრუნებული</option>
              </select>
            </div>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">რეგიონი</label>
            <input :value="extractionFee.region" class="input input-bordered max-w-xs input-sm mb-2 focus:outline-0"
                   disabled>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">მ/ც</label>
            <div class="relative max-w-xs">
              <input type="text" v-model="searchTerm" placeholder="აირჩიეთ მ/ც" @focus="isDropdownOpen = true"
                     @blur="closeDropdown" class="input input-bordered input-sm mb-2 focus:outline-0 w-full"/>

              <!-- Dropdown options -->
              <div v-if="isDropdownOpen && filteredServiceCenters.length"
                   class="absolute z-10 bg-white border border-gray-300 rounded-md shadow-lg mt-1">
                <div v-for="(center, index) in filteredServiceCenters" :key="index"
                     @mousedown="selectCenter(center.name, center.parent.name)"
                     class="p-2 hover:bg-gray-100 cursor-pointer">
                  {{ center.name }}
                </div>
              </div>
            </div>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">პროექტის N</label>
            <input type="text" class="input input-bordered w-full max-w-xs input-sm focus:outline-0"
                   v-model="extractionFee.projectID"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">ტიპი</label>
            <select class="select select-bordered select-sm w-full max-w-xs focus:outline-0"
                    v-model="extractionFee.withdrawType">
              <option disabled selected>აირჩიეთ ტიპი</option>
              <option :value="extractStartingNumber(type)" v-for="(type, index) in withdrawTypes.slice(0, 16)"
                      v-text="type" :key="index"/>
            </select>
          </div>
          <div v-if="extractionFee.withdrawType === '6'" class="flex items-center gap-x-2.5">
            <input type="date" class="text-sm" v-model="extractionFee.paymentOrderSentDate"/>

            <input type="date" class="text-sm" v-model="extractionFee.treasuryRefundDate"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">შენიშვნა</label>
            <textarea v-if="extractionFee"
                      class="textarea textarea-bordered textarea-xs w-full max-w-xs focus:outline-0 resize-none"
                      v-model="extractionFee.note"></textarea>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">გაუქმებული პროექტები</label>
            <textarea v-if="extractionFee"
                      placeholder="პროექტები გამოყავით სფეისით"
                      class="textarea textarea-bordered textarea-xs w-full max-w-xs focus:outline-0 resize-none"
                      v-model="canceledProject"></textarea>
          </div>
        </div>

        <!-- Right Column -->
        <div class="flex flex-col justify-between w-1/2 gap-y-2">
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">გარკვევის თარიღი</label>
            <div v-text="extractionFee.clarificationDate ? formatDate(extractionFee.clarificationDate) : ''"/>
          </div>
          <!--<div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">ცვლილების თარიღი</label>
            <div>
              <p v-text="extractionFee.changeDate ? formatDate(extractionFee.changeDate, true) : ''" />
              <p class="text-neutral underline font-bold" v-if="extractionFee.changeDate"
                v-text="`${extractionFee.changePerson?.firstName} ${extractionFee.changePerson?.lastName}`" />
            </div>
          </div>-->
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">გადმოტანის თარიღი</label>
            <div>
              <p v-text="extractionFee.transferDate ? formatDate(extractionFee.transferDate, true) : ''"/>
              <p v-if="extractionFee.transferPerson" class="text-neutral underline font-bold"
                 v-text="`${extractionFee.transferPerson.firstName} ${extractionFee.transferPerson.lastName}`"/>
            </div>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">ჩარიცხვის თარიღი</label>
            <div v-text="extractionFee.extractionDate ? formatDate(extractionFee.extractionDate) : ''"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">ბრუნვა</label>
            <div v-text="extractionFee.totalAmount"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">დანიშნულება</label>
            <div v-text="extractionFee.purpose"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">დამატებიტი ინფორმაცია</label>
            <div v-text="extractionFee.description"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">თანხის დაბრუნებაზე ხაზინაში მოთხოვნის გაგზავნის თარიღი</label>
            <div
                v-text="extractionFee.paymentOrderSentDate ? formatDate(extractionFee.paymentOrderSentDate) : ''"/>
          </div>
          <div class="flex flex-col gap-y-2">
            <label class="font-semibold text-gray-600">საგადახდო დავალების გაგზავნის თარიღი</label>
            <div v-text="extractionFee.treasuryRefundDate ? formatDate(extractionFee.treasuryRefundDate) : ''"/>
          </div>
        </div>
      </div>

      <span class="text-error" v-if="_error">გთხოვთ შეავსოთ ყველა სავადლებულო ველი!</span>

      <div class="flex items-center justify-between mt-4">
        <div class="flex justify-between items-center">
          <div class="modal-action">
            <button class="btn btn-neutral" @click="handleSaveClick">შენახვა</button>

            <button class="btn btn-warning" @click="handleClearClick">გასუფთავება</button>

            <!--            <button class="btn btn-info text-white" -->
            <!--                    @click="similarPage = 1; fetchSimilarPayments()" -->
            <!--                    onclick="similar_payments_modal.showModal()">-->
            <!--              მსგავსი ჩარიცხვები-->
            <!--            </button>-->

            <button class="btn btn-error text-white"
                    onclick="document.getElementById('delete_transaction_modal').showModal();">წაშლა
            </button>
          </div>
        </div>

        <button class="btn" @click="searchTerm = ''; canceledProject = ''; wasCleared = false;" onclick="my_modal_1.close()">გაუქმება
        </button>
      </div>
    </div>
  </dialog>

  <confirm id="delete_transaction_modal" @accept="hdc"/>

  <dialog id="my_modal_7" class="modal">
    <div class="modal-box">
      <form method="dialog">
        <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2 focus:outline-none">✕</button>
      </form>
      <h3 class="text-lg font-bold" v-text="`გთხოვთ შეიყვანოთ თანხა! ნაშთი ${remainder}`"/>
      <div class="modal-action items-center">
        <input class="input input-bordered w-full max-w-xs input-sm focus:outline-0" type="text" v-model="amount"
               placeholder="10 25 50"/>
        <form method="dialog" class="flex items-center justify-end w-full gap-x-5">
          <button class="btn btn-neutral btn-sm" v-text="'გაყოფა'" :disabled="!validateAmount()"
                  @click="handleDivision"/>
          <button class="btn btn-sm" v-text="'გაუქმება'"/>
        </form>
      </div>
    </div>
  </dialog>

  <dialog id="similar_payments_modal" class="modal">
    <div class="modal-box w-[80vw] h-[80vh] max-w-none flex flex-col">
      <!--      <div class="flex justify-between items-center mb-4">-->
      <!--        <h3 class="font-bold text-lg">მსგავსი ჩარიცხვები</h3>-->
      <!--        <form method="dialog">-->
      <!--          <button class="btn btn-sm btn-circle btn-ghost">✕</button>-->
      <!--        </form>-->
      <!--      </div>-->

      <div v-if="similarLoading" class="flex justify-center my-4 flex-grow">
        <span class="loading loading-spinner loading-lg"></span>
      </div>

      <div v-else class="overflow-y-auto flex-grow">
        <table class="table table-xs table-pin-rows">
          <thead>
          <tr>
            <th>ID</th>
            <th>რეგიონი</th>
            <th>მ/ც</th>
            <th>Tax ID</th>
            <th>თანხა</th>
          </tr>
          </thead>
          <tbody>
          <tr v-for="payment in similarPayments" :key="payment.id">
            <td>{{ payment.id }}</td>
            <td>{{ payment.region }}</td>
            <td>{{ payment.serviceCenter }}</td>
            <td>{{ payment.tax }}</td>
            <td>{{ payment.totalAmount }}</td>
          </tr>
          <tr v-if="similarPayments.length === 0">
            <td colspan="5" class="text-center">ჩანაწერები არ მოიძებნა</td>
          </tr>
          </tbody>
        </table>
      </div>

      <div class="mt-4">
        <pagination
            :absolute="true"
            v-model:current-page="similarPage"
            v-model:page-size="similarPageSize"
            v-model:total-pages="similarTotalPages"
            v-model:total-elements="similarTotalElements"
        />
      </div>
    </div>
  </dialog>
</template>

<style scoped>
/* we will explain what these classes do next! */
.v-enter-active,
.v-leave-active {
  transition: opacity 0.3s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>

// epg-dms-angular/src/app/views/transactions/transactions.ts
import { Component, inject, ChangeDetectorRef, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/auth.service';
import { TransactionsService } from '../../core/transactions.service';
import { FilterDate } from '../../components/filter-date/filter-date';
import { UserSelect } from '../../components/user-select/user-select';
import { RecursiveRow } from '../../components/recursive-row/recursive-row';
import { Pagination } from '../../components/pagination/pagination';
import { Confirm } from '../../components/modals/confirm/confirm';

interface SortOption { text: string; by: string; dir: string; }

@Component({
  selector: 'app-transactions',
  imports: [FormsModule, FilterDate, UserSelect, RecursiveRow, Pagination, Confirm],
  templateUrl: './transactions.html',
  styleUrl: './transactions.css'
})
export class Transactions implements OnInit {
  private api = inject(TransactionsService);
  private auth = inject(AuthService);
  private cdr = inject(ChangeDetectorRef);

  isVisible = false;
  isTypeDropdownOpen = false;

  regions: any[] = [];
  _regions: any[] = [];
  _serviceCenters: any[] = [];
  records: any[] | undefined = [];

  user: any = null;
  currentPage = 1;
  pageSize = 20;
  totalPages = 1;
  totalElements = 20;

  sortBy: string | undefined;
  sortDir: string | undefined;

  _error = false;
  searchTerm = '';
  isDropdownOpen = false;
  canceledProject = '';
  sc: any[] = [];

  amount = '';
  remainder: number | undefined;
  divideId: any;

  similarPayments: any[] = [];
  similarPage = 1;
  similarPageSize = 10;
  similarTotalPages = 0;
  similarTotalElements = 0;
  similarLoading = false;

  extractionFee: any = {
    orderN: '', orderStatus: null, region: '', serviceCenter: '', projectID: '',
    withdrawType: '', note: '', tax: '', totalAmount: '', purpose: '', description: '',
    clarificationDate: null, transferDate: null, extractionDate: null,
    paymentOrderSentDate: null, treasuryRefundDate: null, transferPerson: null
  };

  filter: any = {
    region: 'აირჩიეთ რეგიონი',
    serviceCenter: 'აირჩიეთ მ/ც',
    withdrawType: [],
    status: 'ჩანაწერის სტატუსი',
    orderStatus: 'ორდერის სტატუსი',
    totalAmountStart: undefined,
    totalAmountEnd: undefined,
    orderN: '',
    projectID: '',
    id: '',
    purpose: '',
    tax: '',
    description: '',
    clarificationDateStart: undefined,
    clarificationDateEnd: undefined,
    transferDateStart: undefined,
    transferDateEnd: undefined,
    extractionDateStart: undefined,
    extractionDateEnd: undefined,
    note: '',
    history: '',
    change_person: undefined,
  };

  withdrawTypes: string[] = [
    '1 (პირველი გადახდა)',
    '2 (მეორე გადახდა)',
    '3 (სრული საფასურის გადახდა)',
    '4 (ერთანი გადახდა, გადანაწილებული რამოდენიმე პროექტის საფასურად)',
    '5 (სავარაუდოდ არაა ახალი მიერთების საფასური)',
    '6 (თანხის დაბრუნება)',
    '7 (გადანაწილებული გადახდა / რამოდენიმეჯერ გადახდა)',
    '8 (სააბონენტო ბარათზე თანხის დასმა)',
    '9 (ხაზის მშენებლობა / არარეგულირებული პროექტები (პირველი ან სრული გადახდა))',
    '10 (სისტემის ნებართვის საფასური)',
    '19 (ხაზის მშენებლობა / არარეგულირებული პროექტები (მეორე გადახდა))',
    '11 (მიწოდებიდან გადმოტანილი თანხა)',
    '12 (ჯარიმის გადატანა)',
    '13 (საპროექტო ტრასის შეტანხმება)',
    '14 (ჰესები DDSH)',
    '15 (ჰესები DDNA)',
    'null'
  ];

  sortOptions: SortOption[] = [
    { text: 'N კლებადი', by: 'id', dir: 'DESC' },
    { text: 'N ზრდადი', by: 'id', dir: 'ASC' },
    { text: 'ორდერის N კლებადი', by: 'orderN', dir: 'DESC' },
    { text: 'ორდერის N ზრდადი', by: 'orderN', dir: 'ASC' },
    { text: 'რეგიონი კლებადი', by: 'region', dir: 'DESC' },
    { text: 'რეგიონი ზრდადი', by: 'region', dir: 'ASC' },
    { text: 'მ/ც კლებადი', by: 'serviceCenter', dir: 'DESC' },
    { text: 'მ/ც ზრდადი', by: 'serviceCenter', dir: 'ASC' },
    { text: 'პროექტის N კლებადი', by: 'projectID', dir: 'DESC' },
    { text: 'პროექტის N ზრდადი', by: 'projectID', dir: 'ASC' },
    { text: 'ტიპი კლებადი', by: 'withdrawType', dir: 'DESC' },
    { text: 'ტიპი ზრდადი', by: 'withdrawType', dir: 'ASC' },
    { text: 'გარკვევის თარიღი კლებადი', by: 'clarificationDate', dir: 'DESC' },
    { text: 'გარკვევის თარიღი ზრდადი', by: 'clarificationDate', dir: 'ASC' },
    { text: 'გადმოტანის თარიღი კლებადი', by: 'transferDate', dir: 'DESC' },
    { text: 'გადმოტანის თარიღი ზრდადი', by: 'transferDate', dir: 'ASC' },
    { text: 'ჩარიცხვის თარიღი კლებადი', by: 'extractionDate', dir: 'DESC' },
    { text: 'ჩარიცხვის თარიღი ზრდადი', by: 'extractionDate', dir: 'ASC' },
    { text: 'ბრუნვა კლებადი', by: 'totalAmount', dir: 'DESC' },
    { text: 'ბრუნვა თანხა ზრდადი', by: 'totalAmount', dir: 'ASC' },
  ];

  sortByDir: SortOption = this.sortOptions[16];

  async ngOnInit(): Promise<void> {
    this.user = this.auth.user();
    await this.loadRegions();
    await this.getFees();
    await this.loadServiceCenters();
  }

  async loadRegions(parentId = 68): Promise<void> {
    try {
      const res: any = await this.api.getRegionsByParentId(parentId);
      if (parentId === 68) {
        this.regions = res.data;
        this._regions = res.data;
      } else {
        this._serviceCenters = res.data;
      }
      this.cdr.markForCheck();
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  }

  async loadServiceCenters(): Promise<void> {
    try {
      this.sc = await this.api.getServiceCenters();
      this.cdr.markForCheck();
    } catch (error) {
      console.error('Error service centers data:', error);
    }
  }

  async getFees(): Promise<void> {
    this.records = undefined;
    this.cdr.markForCheck();
    const params = this.api.buildParams(this.filter, {
      sortBy: this.sortBy,
      sortDir: this.sortDir,
      page: this.currentPage,
      size: this.pageSize
    });
    try {
      const data: any = await this.api.getFees(params);
      this.records = data.content;
      this.addShowProperty();
      this.totalPages = data.page.totalPages;
      this.totalElements = data.page.totalElements;
    } catch (error) {
      console.error('Error fetching sheets:', error);
    }
    this.cdr.markForCheck();
  }

  private addShowProperty(): void {
    const stack = [...(this.records ?? [])];
    while (stack.length > 0) {
      const record = stack.pop();
      record.show = false;
      const remainderChild = record.children.filter((c: any) => c.status === 'REMINDER');
      if (record.children && record.children.length > 0) {
        record.remainder = remainderChild.length > 0 ? remainderChild[0].totalAmount : 0;
        stack.push(...record.children);
      } else {
        record.remainder = record.totalAmount;
      }
    }
  }

  async handleEditClick(extraction: any): Promise<void> {
    this._error = false;
    this.searchTerm = extraction.serviceCenter;
    this.canceledProject = (extraction.canceledProject ?? []).join(' ');
    this.extractionFee = { ...extraction };

    (document.getElementById('my_modal_1') as HTMLDialogElement).showModal();

    if (!this.extractionFee.region) {
      this.extractionFee.region = 'აირჩიეთ რეგიონი';
    } else {
      const match = this.regions.find(r => r.name === extraction.region);
      if (match) await this.loadRegions(match.id);
    }

    if (!this.extractionFee.serviceCenter) {
      this.extractionFee.serviceCenter = 'აირჩიეთ მ/ც';
    }

    if (!this.extractionFee.withdrawType) {
      this.extractionFee.withdrawType = 'აირჩიეთ ტიპი';
    }

    this.cdr.markForCheck();
  }

  handleDivideClick(args: any[]): void {
    (document.getElementById('my_modal_7') as HTMLDialogElement).showModal();
    this.divideId = args[0];
    this.remainder = args[1];
    this.cdr.markForCheck();
  }

  async getSelectedParentId(event: Event): Promise<void> {
    const opt = (event.target as HTMLSelectElement).selectedOptions[0];
    await this.loadRegions(Number(opt.getAttribute('data-id')));
  }

  async handleFilter(): Promise<void> {
    this.currentPage = 1;
    await this.getFees();
  }

  async handleClear(): Promise<void> {
    this.filter = {
      region: 'აირჩიეთ რეგიონი', serviceCenter: 'აირჩიეთ მ/ც', withdrawType: [],
      status: 'ჩანაწერის სტატუსი', orderStatus: 'ორდერის სტატუსი',
      totalAmountStart: undefined, totalAmountEnd: undefined,
      orderN: '', projectID: '', id: '', purpose: '', tax: '', description: '',
      clarificationDateStart: undefined, clarificationDateEnd: undefined,
      transferDateStart: undefined, transferDateEnd: undefined,
      extractionDateStart: undefined, extractionDateEnd: undefined,
      note: '', history: '', change_person: undefined
    };
    this._serviceCenters = [];
    this.clearSortByDir();
    await this.handleFilter();
  }

  async onSortChange(): Promise<void> {
    this.sortBy = this.sortByDir.by;
    this.sortDir = this.sortByDir.dir;
    this.currentPage = 1;
    await this.getFees();
  }

  async onPageChange(page: number): Promise<void> {
    this.currentPage = page;
    await this.getFees();
  }

  async onPageSizeChange(size: number): Promise<void> {
    this.pageSize = size;
    this.currentPage = 1;
    await this.getFees();
  }

  get filteredServiceCenters(): any[] {
    return this.sc.filter(c => c.name.toLowerCase().includes(this.searchTerm));
  }

  closeDropdown(): void {
    setTimeout(() => this.isDropdownOpen = false, 200);
  }

  selectCenter(centerName: string, parentName: string): void {
    this.extractionFee.serviceCenter = centerName;
    this.searchTerm = centerName;
    this.extractionFee.region = parentName;
    this.isDropdownOpen = false;
  }

  formatDate(dateString: string, includeTime = false): string {
    const date = new Date(dateString);
    const day = date.getDate().toString().padStart(2, '0');
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const year = date.getFullYear();
    if (includeTime) {
      const h = date.getHours().toString().padStart(2, '0');
      const m = date.getMinutes().toString().padStart(2, '0');
      const s = date.getSeconds().toString().padStart(2, '0');
      return `${day}.${month}.${year} ${h}:${m}:${s}`;
    }
    return `${day}.${month}.${year}`;
  }

  validateAmount(): boolean {
    const regex = /^(\d+(\.\d+)?(\s\d+(\.\d+)?)*)$/;
    const clean = this.amount.replace(/\s+/g, ' ').trim();
    const numbers = clean.split(' ').map(Number);
    const sum = numbers.reduce((a, b) => a + b, 0);
    return regex.test(clean) && numbers.every(n => n > 0) && sum <= (this.remainder ?? 0);
  }

  extractStartingNumber(type: string): string {
    if (type === 'null') return type;
    const match = type.match(/^\d+/);
    return match ? match[0] : '';
  }

  toggleType(type: string): void {
    const index = this.filter.withdrawType.indexOf(type);
    if (index === -1) {
      this.filter.withdrawType.push(type);
    } else {
      this.filter.withdrawType.splice(index, 1);
    }
  }

  clearRegion(): void {
    this.filter.region = 'აირჩიეთ რეგიონი';
    this._serviceCenters = [];
    this.clearSC();
  }

  clearSC(): void { this.filter.serviceCenter = 'აირჩიეთ მ/ც'; }
  clearType(): void { this.filter.withdrawType = []; }
  clearStatus(): void { this.filter.status = 'ჩანაწერის სტატუსი'; }
  clearOrderStatus(): void { this.filter.orderStatus = 'ორდერის სტატუსი'; }
  clearSortByDir(): void { this.sortByDir = this.sortOptions[16]; }

  clearClarification(): void {
    this.filter.clarificationDateStart = undefined;
    this.filter.clarificationDateEnd = undefined;
  }

  clearTransfer(): void {
    this.filter.transferDateStart = undefined;
    this.filter.transferDateEnd = undefined;
  }

  clearExtraction(): void {
    this.filter.extractionDateStart = undefined;
    this.filter.extractionDateEnd = undefined;
  }
  wasCleared = false;

  handleClearClick(): void {
    this.wasCleared = true;
    this._error = false;
    this.extractionFee.orderN = '';
    this.extractionFee.orderStatus = null;
    this.extractionFee.projectID = '';
    this.extractionFee.withdrawType = 'აირჩიეთ ტიპი';
    this.extractionFee.paymentOrderSentDate = null;
    this.extractionFee.treasuryRefundDate = null;
    this.extractionFee.clarificationDate = null;
    this.extractionFee.note = '';
    this.searchTerm = '';
    this.extractionFee.region = 'აირჩიეთ რეგიონი';
    this.extractionFee.serviceCenter = 'აირჩიეთ მ/ც';
    this.canceledProject = '';
  }

  private clearPlaceholders(): void {
    if (this.extractionFee.region === 'აირჩიეთ რეგიონი' || this.extractionFee.region === '') {
      this.extractionFee.region = '';
    }
    if (this.extractionFee.serviceCenter === 'აირჩიეთ მ/ც') {
      this.extractionFee.serviceCenter = '';
    }
    if (this.extractionFee.withdrawType === 'აირჩიეთ ტიპი') {
      this.extractionFee.withdrawType = '';
    }
  }

  private async performSaveActions(): Promise<void> {
    const trimmed = this.canceledProject.trim();
    this.extractionFee.canceledProject = trimmed === '' ? [] : trimmed.split(/\s+/);
    this.canceledProject = '';
    this.wasCleared = false;

    try {
      const body = { ...this.extractionFee };
      delete body.changePerson;
      delete body.transferPerson;
      if (!body.note) body.note = '';
      if (!body.projectID) body.projectID = '';
      if (!body.orderStatus) body.orderStatus = null;
      await this.api.updateRecord(body.id, body);
    } catch (error) {
      console.error('Error updating fee:', error);
    }

    await this.getFees();
    this.searchTerm = '';
    (document.getElementById('my_modal_1') as HTMLDialogElement).close();
    this.cdr.markForCheck();
  }

  async handleSaveClick(): Promise<void> {
    const { region, withdrawType, serviceCenter, projectID, orderN } = this.extractionFee;
    const isRefund = withdrawType === '6 (თანხის დაბრუნება)';
    const isAdmin = this.auth.user()?.role === 'ROLE_ADMIN';
    const isTypeException = (orderN ?? '').trim().toUpperCase() === 'N/A';

    const isRegionInvalid = !isRefund && region === 'აირჩიეთ რეგიონი';
    const isServiceCenterInvalid = !isRefund && serviceCenter === 'აირჩიეთ მ/ც';
    const isWithdrawTypeInvalid = withdrawType === 'აირჩიეთ ტიპი';
    const isProjectInvalid = !isAdmin && !projectID;

    const isInvalid = isRegionInvalid || isServiceCenterInvalid || isWithdrawTypeInvalid || isProjectInvalid;

    if (this.wasCleared) {
      this.clearPlaceholders();
      await this.performSaveActions();
    } else if (isTypeException) {
      this.clearPlaceholders();
      if (!this.extractionFee.orderStatus || this.extractionFee.orderStatus === 'ORDER_INCOMPLETE') {
        this.extractionFee.orderStatus = 'ORDER_COMPLETE';
      }
      await this.performSaveActions();
    } else if (isInvalid) {
      if (this.canceledProject) {
        this.clearPlaceholders();
        await this.performSaveActions();
      } else {
        this._error = true;
        this.cdr.markForCheck();
      }
    } else {
      await this.performSaveActions();
    }
  }

  async hdc(): Promise<void> {
    this.canceledProject = '';
    try {
      await this.api.deleteRecord(this.extractionFee.id);
    } catch (error) {
      console.error(error);
    }
    await this.getFees();
    (document.getElementById('my_modal_1') as HTMLDialogElement).close();
    this.cdr.markForCheck();
  }

  async handleDivision(): Promise<void> {
    const amounts = this.amount.replace(/\s+/g, ' ').trim().split(' ').map(Number);
    try {
      await this.api.divide(this.divideId, amounts);
    } catch (error) {
      console.error(error);
    }
    await this.getFees();
    this.divideId = undefined;
    this.amount = '';
    this.remainder = undefined;
    this.cdr.markForCheck();
  }

  cancelModal(): void {
    this.searchTerm = '';
    this.canceledProject = '';
    this.wasCleared = false;
    (document.getElementById('my_modal_1') as HTMLDialogElement).close();
  }

  openDeleteModal(): void {
    (document.getElementById('delete_transaction_modal') as HTMLDialogElement).showModal();
  }
}
